services:
  - name: web
    type: web
    plan: starter
    envVars:
      - key: RAILS_ENV
        value: production
    buildCommand: bundle install --without development:test
    startCommand: bundle exec rails server -p $PORT
    healthCheckPath: /healthcheck
    httpPort: 8080
    instanceCount: 1
    workingDirectory: /app
    
